# Generated by Django 3.2.5 on 2021-09-07 16:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('planId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('quota', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('useranme', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20, null=True)),
                ('lastName', models.CharField(max_length=20, null=True)),
                ('phoneNumber', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('email1', models.EmailField(max_length=20)),
                ('email2', models.EmailField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('securityPin', models.IntegerField(null=True)),
                ('accountCreationDate', models.DateTimeField()),
                ('planId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primal_user.plans')),
            ],
        ),
    ]
