# Generated by Django 3.2.5 on 2021-09-08 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('assetId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('assetName', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True)),
                ('uploadedDate', models.DateField(auto_now_add=True)),
                ('typeId', models.BooleanField(default=True)),
                ('paidStatus', models.BooleanField(default=False)),
                ('price', models.IntegerField(null=True)),
                ('size', models.FloatField()),
                ('downloadCount', models.BigIntegerField(null=True)),
                ('version', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('keywordId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='useranme',
            new_name='userName',
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('historyId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('keywordId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primal_user.tags')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primal_user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('rating', models.FloatField(null=True)),
                ('comment', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('assetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primal_user.asset')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primal_user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('cartId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('orderId', models.CharField(max_length=20)),
                ('transactionId', models.CharField(max_length=50)),
                ('success', models.BooleanField(default=False)),
                ('purchaseDate', models.DateField(auto_now_add=True)),
                ('assetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primal_user.asset')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primal_user.user')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='devUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primal_user.user'),
        ),
        migrations.AddField(
            model_name='asset',
            name='keywordId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primal_user.tags'),
        ),
    ]
