# Generated by Django 3.2.5 on 2021-09-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='planId',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
