# Generated by Django 3.2.5 on 2021-09-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0002_auto_20210908_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assetsDownloaded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='assetsPurchased',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='googleId',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='imageURL',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email1',
            field=models.EmailField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='email2',
            field=models.EmailField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
