# Generated by Django 3.2.5 on 2021-09-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0002_auto_20210909_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email1',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='email2',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='googleId',
            field=models.CharField(default='', max_length=512, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='imageURL',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='securityPin',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
