# Generated by Django 3.2.5 on 2021-09-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0002_alter_plans_planid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='planId',
        ),
    ]
