# Generated by Django 3.2.5 on 2021-09-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0003_auto_20210909_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accountCreationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
