# Generated by Django 3.2.5 on 2021-09-09 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0004_alter_user_accountcreationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='planId',
            field=models.CharField(default='Free', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='planId',
            field=models.ForeignKey(default='Free', on_delete=django.db.models.deletion.CASCADE, to='primal_user.plans'),
        ),
    ]
