# Generated by Django 3.2.5 on 2021-09-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0005_auto_20210909_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='quota',
            field=models.CharField(default='100MB', max_length=10),
        ),
    ]
