# Generated by Django 3.2.5 on 2021-09-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0008_alter_user_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='slug',
            field=models.SlugField(blank=True, max_length=522, null=True),
        ),
    ]
