# Generated by Django 3.2.5 on 2021-09-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0009_auto_20210916_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='securityPin',
            new_name='password',
        ),
    ]
