# Generated by Django 3.2.5 on 2021-09-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0009_asset_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='slug',
        ),
    ]
