# Generated by Django 3.2.5 on 2021-09-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0010_remove_asset_slug'),
        ('primal_user', '0010_rename_securitypin_user_password'),
    ]

    operations = [
    ]
