# Generated by Django 3.2.5 on 2021-09-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0011_merge_20210918_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assetId',
            field=models.CharField(max_length=512, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetName',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='order',
            name='cartId',
            field=models.CharField(max_length=512, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='plans',
            name='planId',
            field=models.CharField(default='Free', max_length=512, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewId',
            field=models.CharField(max_length=512, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='historyId',
            field=models.CharField(max_length=512, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tags',
            name='keyword',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='tags',
            name='keywordId',
            field=models.CharField(max_length=512, primary_key=True, serialize=False),
        ),
    ]
