# Generated by Django 3.2.5 on 2021-09-22 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0012_auto_20210922_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='keywordId',
        ),
        migrations.CreateModel(
            name='RelatedTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primal_user.asset')),
                ('keywordId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primal_user.tags')),
            ],
        ),
    ]
