# Generated by Django 3.2.5 on 2021-09-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0013_auto_20210922_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='uploadedDate',
            new_name='createdDate',
        ),
        migrations.AddField(
            model_name='asset',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
