# Generated by Django 3.2.7 on 2021-10-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0015_auto_20211005_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='size',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='asset',
            name='version',
            field=models.CharField(default='1.0.0', max_length=10),
        ),
    ]
