# Generated by Django 3.2.7 on 2021-10-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0016_auto_20211006_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='paidStatus',
        ),
    ]
