# Generated by Django 3.2.7 on 2021-10-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0017_remove_asset_paidstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewId',
            field=models.AutoField(max_length=512, primary_key=True, serialize=False),
        ),
    ]
