# Generated by Django 3.2.7 on 2021-10-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0018_alter_review_reviewid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
