# Generated by Django 3.2.7 on 2021-10-12 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0019_alter_review_reviewid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thubnailURL', models.CharField(max_length=512)),
                ('assetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primal_user.asset')),
            ],
        ),
    ]
