# Generated by Django 3.2.7 on 2021-10-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0020_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbnail',
            old_name='thubnailURL',
            new_name='thumbnailURL',
        ),
    ]
