# Generated by Django 3.2.7 on 2021-10-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0021_rename_thubnailurl_thumbnail_thumbnailurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='id',
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='thumbnailURL',
            field=models.CharField(max_length=512, primary_key=True, serialize=False),
        ),
    ]
