# Generated by Django 3.2.7 on 2021-10-13 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0022_auto_20211012_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvgReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avgRating', models.FloatField(null=True)),
                ('assetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primal_user.asset')),
            ],
        ),
    ]
