# Generated by Django 3.2.7 on 2021-10-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0023_avgreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='avgRating',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='AvgReview',
        ),
    ]
