# Generated by Django 3.2.7 on 2021-10-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0024_auto_20211013_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cartId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
