# Generated by Django 3.2.7 on 2021-10-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0025_alter_order_cartid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transactionId',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
