# Generated by Django 3.2.7 on 2021-10-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0026_alter_order_transactionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transactionId',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
