# Generated by Django 3.2.7 on 2021-11-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0028_auto_20211026_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accountNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ifsc',
            field=models.IntegerField(null=True),
        ),
    ]
