# Generated by Django 3.2.7 on 2021-11-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0029_auto_20211102_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accountNumber',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ifsc',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
