# Generated by Django 3.2.7 on 2021-11-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0030_auto_20211102_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
