# Generated by Django 3.2.7 on 2021-11-03 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primal_user', '0031_order_bought'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primal_user.asset')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primal_user.user')),
            ],
        ),
    ]
